server:
  port: ${SERVER_PORT:80}

share-folder:
  path: ${SHARE_FOLDER_DIRECTORY:/share}

sparql:
  endpoint: ${SPARQL_ENDPOINT:http://database:8890/sparql}
  defaultGraphUri: ${TARGET_GRAPH:http://mu.semte.ch/application}
  defaultBatchSize: ${BATCH_SIZE:100}

spring:
  servlet:
    multipart:
      enabled: true
      max-request-size: ${MAX_REQUEST_SIZE:512MB}
      max-file-size: ${MAX_FILE_SIZE:512MB}

logging:
  level:
    root: ${LOGGING_LEVEL:INFO}
